# Generated by Django 4.1.7 on 2023-03-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiconductor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semiconductor',
            name='sort',
            field=models.CharField(default=1, max_length=50, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
