# Generated by Django 4.1.7 on 2023-04-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiconductor', '0002_semiconductor_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semiconductor',
            name='sort',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
    ]
