# Generated by Django 4.1.7 on 2023-03-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, verbose_name='Código')),
                ('trademark', models.CharField(max_length=150, verbose_name='Marca')),
                ('model', models.CharField(max_length=150, verbose_name='Modelo')),
                ('leds', models.CharField(max_length=10, verbose_name='LEDS')),
                ('voltage', models.CharField(max_length=10, verbose_name='Voltaje')),
                ('piece', models.CharField(max_length=50, verbose_name='Piezas')),
                ('references', models.CharField(max_length=150, verbose_name='Código')),
                ('image', models.ImageField(upload_to='Backlights', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Backlight / Tira LED',
                'verbose_name_plural': 'Backlights / Tira LEDs',
                'ordering': ['code'],
            },
        ),
    ]
