# Generated by Django 4.1.7 on 2023-03-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlight',
            name='references',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Refencia'),
        ),
    ]
