# Generated by Django 4.1.7 on 2023-03-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('model', models.CharField(max_length=150, verbose_name='Modelo')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Herramienta & Accesorio',
                'verbose_name_plural': 'Herramientas & Accesorios',
                'ordering': ['name'],
            },
        ),
    ]
