# Generated by Django 4.1.7 on 2023-04-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(upload_to='Accesorios', verbose_name='Imagen'),
        ),
    ]
