# Generated by Django 4.1.7 on 2023-03-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['code'], 'verbose_name': 'Audio', 'verbose_name_plural': 'Audio'},
        ),
    ]
