# Generated by Django 4.1.7 on 2023-03-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miscellany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, verbose_name='Código')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='Miceláneas', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Micelánea',
                'verbose_name_plural': 'Miceláneas',
                'ordering': ['code'],
            },
        ),
    ]
