# Generated by Django 4.1.7 on 2023-03-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
